/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Out_MAX232.h"
#include "TX1_aliases.h"
#include "TX1.h"
#include "TX2_aliases.h"
#include "TX2.h"
#include "RX_aliases.h"
#include "RX.h"
#include "Test_Ampli_aliases.h"
#include "Test_Ampli.h"
#include "LCD.h"
#include "Timer_TX.h"
#include "Interrupt_TX.h"
#include "Chronometer.h"
#include "Counter_Pulses.h"
#include "Comparator.h"
#include "Threshold.h"
#include "Interrupt_RX.h"
#include "Clk.h"
#include "Pre_Ampli.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "XBee.h"
#include "Rotation_Register.h"
#include "PWM_Front.h"
#include "Clock_1.h"
#include "InhB_Front_Right_aliases.h"
#include "InhB_Front_Right.h"
#include "InhA_Front_Right_aliases.h"
#include "InhA_Front_Right.h"
#include "InhB_Back_Right_aliases.h"
#include "InhB_Back_Right.h"
#include "InhA_Back_Right_aliases.h"
#include "InhA_Back_Right.h"
#include "InhA_Back_Left_aliases.h"
#include "InhA_Back_Left.h"
#include "InhB_Back_Left_aliases.h"
#include "InhB_Back_Left.h"
#include "InhB_Front_Left_aliases.h"
#include "InhB_Front_Left.h"
#include "InhA_Front_Left_aliases.h"
#include "InhA_Front_Left.h"
#include "PWM_Front_Left_aliases.h"
#include "PWM_Front_Left.h"
#include "PWM_Front_Right_aliases.h"
#include "PWM_Front_Right.h"
#include "PWM_Back.h"
#include "Clock_2.h"
#include "PWM_Back_Left_aliases.h"
#include "PWM_Back_Left.h"
#include "PWM_Back_Right_aliases.h"
#include "PWM_Back_Right.h"
#include "Interrupt_Xbee.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "XBee_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

